Uniswap/v3-staker

contracts/UniswapV3Staker.sol, contracts/libraries/Helper.sol, contracts/libraries/IncentiveHelper.sol, contracts/test/TestIncentiveID.sol, test/UniswapV3Staker.unit.spec.ts
=> Refactors getIncentiveId visibility

contracts/UniswapV3Staker.sol, test/UniswapV3Staker.unit.spec.ts
Basically, when returning from multi-stake to uno-stake, I could've refactored better. SO here it is now.
=> refactor stake to be DRYer

contracts/UniswapV3Staker.sol, package.json, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/shared/fixtures.ts, yarn.lock
closes https://github.com/omarish/uniswap-v3-staker/issues/40
=> Extend Multicall + revert bug fix

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/Accounting.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/helpers/index.ts
=> Unstake and claim

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/Accounting.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/shared/index.ts
closes https://github.com/omarish/uniswap-v3-staker/issues/66
=> stakeToken caches current liquidity + reverts based on invalid timing

contracts/UniswapV3Staker.sol, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
=> Using TransferHelper safe transfer functions for ERC20

test/UniswapV3Staker.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/helpers/index.ts, test/helpers/types.ts, test/shared/fixtures.ts, test/shared/index.ts, types/contractParams.ts
- createIncentive tests cleanup
- endIncentive tests
- Fixes depositToken tests
- Cleanup stake/unstake tests
=> Refactors Unit Tests

contracts/UniswapV3Staker.sol, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/shared/fixtures.ts
=> Fixes unstakeToken

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, contracts/libraries/IncentiveHelper.sol
Closes #71 
@omarish @ewilz  What do we think about renaming `claimDeadline`. Currently I understand it as the time where an incentive creator can get the remaining rewards back from the contract after the incentive has been completed. I think deadline implies that it has to be done before. 
TODO:
=> Adds natspec annotations

contracts/UniswapV3Staker.sol, test/UniswapV3Staker.unit.spec.ts
- Updated revert messages
- Updates tests
=> Standardizes revert messages

contracts/UniswapV3Staker.sol, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
closes https://github.com/omarish/uniswap-v3-staker/issues/86
lots of extra changes due to running linter on ts files... :(
=> Allow stakers to unstake against deleted incentives

contracts/UniswapV3Staker.sol, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
closes https://github.com/omarish/uniswap-v3-staker/issues/39
=> get rid of nonreentrant

contracts/UniswapV3Staker.sol, docs/Design.md, package.json, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
Updates design doc to match current implementation.
=> Updates Design Doc

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, docs/Design.md, test/UniswapV3Staker.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/helpers/index.ts, types/contractParams.ts
fixes https://github.com/omarish/uniswap-v3-staker/issues/125
=> remove exists from stake

contracts/UniswapV3Staker.sol, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
I was giving the contract a really close read through and these two lines popped out. I think the answer is that it's fine, but what do you think of the change in line placement here?
=> Security questions: increment/decrement numberOfStakes

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, contracts/libraries/IncentiveId.sol
fixes https://github.com/omarish/uniswap-v3-staker/issues/138
=> Typed addresses

test/UniswapV3Staker.integration.spec.ts, test/matchers/beWithin.ts, test/types.ts
- Adds beWithin matcher
- Closes #142
=> Adds Approximate BN Matching

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, contracts/test/TestIncentiveId.sol, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/helpers/index.ts, test/shared/fixtures.ts
Reverts omarish/uniswap-v3-staker#113
=> Revert "Update Stake and claim reward without unstaking"

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, docs/Design.md, test/UniswapV3Staker.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, types/contractParams.ts
make getRewardAmount external
secondsInPeriodX128 -> secondsInsideX128
secondsPerLiquidityInitialX128 -> secondsPerLiquidityInsideInitialX128
=> simplify reward math

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, contracts/libraries/IncentiveId.sol, docs/Design.md, test/UniswapV3Staker.integration.spec.ts, test/UniswapV3Staker.unit.spec.ts, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap, test/helpers/index.ts, test/helpers/types.ts, test/shared/index.ts, types/contractParams.ts
this addresses all the checks in the issue
fixes https://github.com/omarish/uniswap-v3-staker/issues/148
=> refactor: removing the claim deadline

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/__snapshots__/UniswapV3Staker.unit.spec.ts.snap
fixes https://github.com/omarish/uniswap-v3-staker/issues/160
=> make reward into a uint256

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/UniswapV3Staker.integration.spec.ts, test/helpers/index.ts, test/unit/Multicall.spec.ts, test/unit/Stakes.spec.ts, test/unit/__snapshots__/Incentives.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
=> Adds claimRewardAmount

contracts/UniswapV3Staker.sol
**Contract sizes**
Before:
| Contract      | Size (Kb) |
| ----------- | ----------- |
| contracts/UniswapV3Staker.sol:UniswapV3Staker      | 12.10       |
After:
| Contract      | Size (Kb) |
| ----------- | ----------- |
| contracts/UniswapV3Staker.sol:UniswapV3Staker      | 12.83       |
Closes #167 
_Aside: It looks like the `revertedWith` Chia assertion does a partial instead of exact match for the reason in the revert messages._
=> Updates revert messages with function names

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/unit/__snapshots__/Deposits.spec.ts.snap, test/unit/__snapshots__/Incentives.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
closes https://github.com/omarish/uniswap-v3-staker/issues/168
=> Add return values for functions that transfer rewards

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/unit/Stakes.spec.ts, test/unit/__snapshots__/Deposits.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
would close https://github.com/omarish/uniswap-v3-staker/issues/164
=> Deposit includes tickLower tickUpper

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, docs/Design.md, test/UniswapV3Staker.integration.spec.ts, test/helpers/index.ts, test/unit/Deposits.spec.ts, test/unit/Multicall.spec.ts, test/unit/__snapshots__/Deposits.spec.ts.snap, test/unit/__snapshots__/Incentives.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap
=> feat: Add data param

contracts/UniswapV3Staker.sol, test/unit/RewardMath/RewardMath.spec.ts, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
unstaking a stake should never encounter the if branch
=> remove unused incentive reward check

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, test/shared/fixtures.ts, test/unit/Deployment.spec.ts, test/unit/Incentives.spec.ts, test/unit/__snapshots__/Deposits.spec.ts.snap, test/unit/__snapshots__/Incentives.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
=> time constrains on createIncentive

.prettierrc, contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, contracts/libraries/IncentiveId.sol, contracts/libraries/NFTPositionInfo.sol, contracts/libraries/RewardMath.sol, contracts/test/TestERC20.sol, contracts/test/TestIncentiveId.sol, test/UniswapV3Staker.integration.spec.ts, test/helpers/index.ts, test/matchers/beWithin.ts, test/shared/external/v3-periphery/ticks.ts, test/shared/external/v3-periphery/tokenSort.ts, test/shared/fixtures.ts, test/shared/index.ts, test/shared/linkLibraries.ts, test/unit/Deployment.spec.ts, test/unit/Deposits.spec.ts, test/unit/Incentives.spec.ts, test/unit/Multicall.spec.ts, test/unit/RewardMath/RewardMath.spec.ts, test/unit/Stakes.spec.ts, types/ISwapRouter.d.ts, types/IWETH9.d.ts, types/NFTDescriptor.d.ts
- Updates prettierrc
- Updates contract line length
- Reformats ts line length
=> Conforms to Uniswap line lengths

.gitignore, .solcover.js, hardhat.config.ts, package.json, yarn.lock
=> Adds test coverage plugin

contracts/UniswapV3Staker.sol, test/unit/__snapshots__/Deposits.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap
=> disallow withdraw to staker

contracts/UniswapV3Staker.sol, contracts/interfaces/IUniswapV3Staker.sol, docs/Design.md
addresses some points here: https://github.com/Uniswap/uniswap-v3-staker/issues/206
=> some extra documentation: onERC721Received + claimRewards

contracts/UniswapV3Staker.sol, contracts/libraries/TransferHelperExtended.sol, test/unit/Incentives.spec.ts, test/unit/__snapshots__/Incentives.spec.ts.snap, test/unit/__snapshots__/Multicall.spec.ts.snap, test/unit/__snapshots__/Stakes.spec.ts.snap
fixes https://github.com/Uniswap/v3-staker/issues/219
=> Use TransferHelperExtended for transfers
